<main>
    <h2>
        Vous avez décidé de passer à l'abordage. Vous ordonnez à vos hommes de lancer les grappins et de poser les planches. Vous vous hâtez de sauter sur le galion et vous vous retrouvez face à un vrai champ de bataille sur le pont de la Licorne. Sur votre droite vous apercevez le bureau du capitaine, sur votre gauche la trappe de la cale est ouverte et personne ne la protège. Enfin, face à vous, vous apercevez à travers la fumée des flammes le capitaine de la Licorne se battant contre vos hommes.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous décidez de
                <select name="choix_pont" id="persoChoice">
                    <option value="bureau">vous précipiter dans le bureau du capitaine pour trouver où se trouve la cargaison secrète</option>
                    <option value="cale">vous diriger vers la cale pour aller chercher la cargaison secrète</option>
                     <option value="capitaine">défier le capitaine</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>