<main>
</p class="paragraphe_cowboy">
    Vous décidez de passer par l'arrière de la maison. Vous avancez avec assurance avec vos camarades. Mais après quelques mètres, vous tombez sur une boite remplie de bijoux et de lingots d'or. Alors que vous vous demandez s'il est nécessaire de continuer d'avancer, vous entendez le tintement d'une chaine et des pas venant de l'étage. Votre sang et celui de vos camarades ne font qu'un tour et en un instant vous prenez vos jambes à votre cou. Cette nuit fut gravée dans l'esprit de vos camarades et vous.
</p>
</main>