<main>
</p>
    Vous décidez de passer par l'arrière de la maison. Vous avencez avec assurance avec vos camarades. Mais après quelques mètres vous tombez sur une boite rempli de bijoux et de lingots d'or. Alors que vous vous demandez si il est necessaire de continué d'avancer, vous entendez le tintement d'une chaine et des pas venir de l'étages. Votre sang et celui de vos camarade ne fait qu'un tour et en un instant vous prenez vos jambes à votre cou. Cette nuit fu gravée dans l'esprit de vos camarades et vous.
</p>
</main>