<main>
    <h2>
        Vous décidez de rattraper les brigands qui s'enfoncent dans les marécages. Plus vous avancez dans la brume, plus le froid vient glacer vos mouvements. Tout d'un coup vous voyez une lumière au loin et la silhouette d'une cabane se dessine.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous décidez de
                <select name="choix_marecage" id="persoChoice">
                    <option value="cabane">vous diriger vers cette mystérieuse cabane.</option>
                    <option value="enfoncer">Continuer de vous enfoncer encore dans la brume.</option>
                    <option value="prier">Prier la où vous vous trouvez</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>