<main>
    <p>
       Vous entrez dans la cabane, à l'intérieur une vieille dame vous y attend. Elle vous dit que rien ne sert de pourchasser les brigands et que leur sort est déjà scellé et que quiconque s'aventure plus loin dans ce marécage n'en ressort jamais. Vous la remerciez de vous avoir prévenu et vous décidez de retourner à votre église pour vous occuper des sépultures de vos confrères et rebâtir ce monument religieux.
    </p>
</main>