<main>
</p>
        Vous ordonnez aux canonniers de se préparer à faire feu. Votre équipage s'active, et les premiers coups de canons se font entendre. L'air est chargé de l'odeur de la poudre à canon. Vous ordonnez de charger les canons avec des boulets incendiaires. La Licorne n'est qu'un brasier d'où s'échappent les hurlements des marins. Vous montez à bord du galion et vous apercevez le capitaine de celui-ci, mort avec le regard désespéré. Grâce à cette attaque frontale, vous pouvez piller sans dérangement toute la cargaison de la Licorne. La cargaison étant en votre possession, vous devenez donc le pirate le plus prospère des mers des Caraïbes.
</p>
</main>