<main>
</p>
        Vous ordonnez aux canoniers de préparer à faire feu. Votre équipage s'active, et les premiers coups de canons se font entendre. L'air est chargé de l'odeur de la poudre à canon. Vous ordonnez de charger les canons avec des boulets incendiers. La Licorne n'est qu'un brasier d'où s'échappe le hurlements des marins. Vous montez à bords du gallion et vous appercevez le capitaine de celui ci, mort avec le regard désesperé. Grâce à cette attaque frontale vous pouvez piller sans dérangements toute la cargaison de la Licorne. La cargaison étant en votre possession vous devenez donc le pirate le plus prospère des mers des caraïbes.
</p>
</main>