<main>
    <h2>
        Vous vous trouvez dans un saloon, l'alcool coule à flot et la musique fait danser tant bien que mal les plus saoul. Vous êtes connu pour gagner vos duel avec seulement une demi balle dans votre chargeur. Une bande de gros bras rentrent dans le saloon en braillant et rigolant. Ils sèment la pagailles dans au bar et vous observez la scènes un whyski à la main.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_saloon" id="persoChoice">
                    <option value="sortir">sortir du bar et de ne pas intervenir</option>
                    <option value="stopper">stopper les agissement des fauteur de troubles</option>
                    <option value="duel">proposer au chef de la bande un duel a l'exterieur du bar</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>