<main>
    <h2>
        
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_eglise" id="persoChoice">
                    <option value="briguand">Lenny Morgan</option>
                    <option value="soeur">Don Jean François</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>