<main>
    <p>
    Vous décidez d'ignorer la cabane et de vous enfoncer encore un peu plus dans les marécages. Au bout de quelques mètres, vous arrivez dans une clairière inondée d'eau et vous observez aux alentours. Stupéfait, vous vous rendez compte que la bande de brigands n'existe plus et qu'il ne reste que d'eux des corps flottant à la surface d'une eau vaseuse et mélangée de la couleur du sang. Et en un clin d'œil la mâchoire d'un alligator vous attrape et vous tire vers le fond. La mort est inévitable, donc dans ce dernier instant de vie vous priez une fois de plus pour pardonner à votre âme de ne pas avoir secouru la bonne sœur restée sous les décombres.
    </p>
</main>