<main>
</p>
        Vous décidez d'hisser les voiles pour tenter de rattraper le gallion mais le vent vous fait dériver et expose votre flan à l'enemi. En un éclair la licorne charge ses canon et une pluie de boulet s'abat sur votre bateau. La fin de l'équipage de Rackam le Rouge est proche et dans un dernier hurlement de haine vous maudissez le capitain de la licorne, lui et les génération qui le précédera.
</p>
</main>