<main>
</p>
        Vous décidez d'hisser les voiles pour tenter de rattraper le galion mais le vent vous fait dériver et expose votre flanc à l'ennemi. En un éclair, la licorne charge ses canons et une pluie de boulets s'abat sur votre bateau. La fin de l'équipage de Rackam le Rouge est proche et dans un dernier hurlement de haine vous maudissez le capitaine de la Licorne, lui et les générations qui le suivront.
</p>
</main>