<main>
    <h2>
        Par une de vos sources d'information, vous avez eu connaissance qu'un galion nommé La Licorne, voguant sur les mers des Caraïbes transportant alcool et tabac, possède en réalité une cargaison secrète. Celle-ci étant cachée au fond de la cale et son existence étant connue que par quelques subordonnés et le capitaine lui-même. Vous vous dirigez donc vers ce bateau, le pavillon noir levé. La licorne vous aperçoit à travers la brume marine et décide de mettre les voiles.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_licorne" id="persoChoice">
                    <option value="abordage">passer à l'abordage</option>
                    <option value="canon">tiré au canon sur le gallion</option>
                    <option value="hisser_voile">hisser les voiles pour rattraper l'avance que le gallion a pris sur vous </option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>