<main>
    <h2>
        Vous vous retrouvez face à votre église détruite par des brigands que vous voyez s'enfuir au loin vers un marécage. Vous apercevez une bonne sœur à moitié morte vous demandant de l'aide.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_eglise" id="persoChoice">
                    <option value="briguand">Courir après les brigands en laissant la bonne soeur pour morte.</option>
                    <option value="soeur">D'aider la bonne soeur à sortir des décombres.</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>