<main>
</p>
        Vous vous mettez à prier. Vous fermez les yeux et les bruits autour de vous s'assourdissent de plus en plus... <br> Puis dans ce silence une voix lointaine vous appelle, elle s'approche de plus en plus. Lorsque vous ouvrez les yeux, vous vous rendez compte que tout cela n'était qu'une vision du futur.<br>

        Grâce à celle-ci, vous arrivez à prévoir l'attaque des brigands et à les repousser à l'aide du seigneur.
</p>
</main>