<main>
    <h2 class="titre_cowboy">
        Vous décidez de sortir du saloon. Comme prévu, vos compagnons vous attendent dans une ruelle adjacente au bar. Vous les rejoignez pour leur parler d'un braquage.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_braquage" id="persoChoice">
                    <option value="banque">leur parler du braquage de la banque</option>
                    <option value="armurie">leur parler du braquage de l'armurie</option>
                    <option value="veuve">leur parler du braquage de la maison d'une riche veuve de la région</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>