<h2>
        Le début de l'aventure...
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <select name="perso" id="persoChoice">
                <option value="cow-boy">Lenny Morgan</option>
                <option value="pretre">Don Jean François</option>
                <option value="pirate">Rackam Le Rouge</option>
            </select>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>