<main>
    <h2>
        Vous décidez de leur parler du braquage de la maison d'une riche veuve. La nuit tombée, vous vous regroupez devant la maison de la veuve.
    </h2>
    <form id="formulaire" method="get" action="index.php">
        <fieldset>
            <p>Vous choisissez de
                <select name="choix_veuve" id="persoChoice">
                    <option value="arriere">passer par l'arrière de la maison</option>
                    <option value="avant">passer par l'avant de la maison</option>
                </select>
            </p>
        </fieldset>
        <fieldset>
        <button type="submit">Choisir</button>
      </fieldset>
    </form>
</main>